<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { Boxes, Plus, Pencil, Trash2 } from '@lucide/vue';
import { api, errorMessage } from '../lib/api'; import StatusBadge from '../components/StatusBadge.vue';
type Product={id:string;sku:string;name:string;category:string;unit:string;costPrice:string;defaultSalePrice:string;minimumStock:number;reorderPoint:number}; type Location={id:string;name:string;type:string;country:string;city:string;address:string;isActive:boolean}; type Row={id:string;quantityOnHand:number;quantityReserved:number;product:Product;location:Location;health:{available:number;status:string}};
const tab=ref<'stock'|'products'|'locations'>('stock'),rows=ref<Row[]>([]),products=ref<Product[]>([]),locations=ref<Location[]>([]),error=ref(''),modal=ref<'product'|'location'|'adjust'|null>(null),editingId=ref('');
const product=reactive({sku:'',name:'',category:'',unit:'unit',costPrice:0,defaultSalePrice:0,minimumStock:0,reorderPoint:0}); const location=reactive({name:'',type:'WAREHOUSE',country:'Egypt',city:'',address:''}); const adjustment=reactive({productId:'',locationId:'',delta:1,reason:'Stock count adjustment'});
async function load(){try{const[a,b,c]=await Promise.all([api.get('/inventory'),api.get('/products',{params:{limit:100}}),api.get('/locations')]);rows.value=a.data.data;products.value=b.data.data;locations.value=c.data.data}catch(e){error.value=errorMessage(e)}}
function addProduct(){editingId.value='';Object.assign(product,{sku:'',name:'',category:'',unit:'unit',costPrice:0,defaultSalePrice:0,minimumStock:0,reorderPoint:0});modal.value='product'} function editProduct(p:Product){editingId.value=p.id;Object.assign(product,{...p,costPrice:Number(p.costPrice),defaultSalePrice:Number(p.defaultSalePrice)});modal.value='product'} async function saveProduct(){try{editingId.value?await api.patch(`/products/${editingId.value}`,product):await api.post('/products',product);modal.value=null;await load()}catch(e){error.value=errorMessage(e)}}
function addLocation(){editingId.value='';Object.assign(location,{name:'',type:'WAREHOUSE',country:'Egypt',city:'',address:''});modal.value='location'} function editLocation(x:Location){editingId.value=x.id;Object.assign(location,x);modal.value='location'} async function saveLocation(){try{editingId.value?await api.patch(`/locations/${editingId.value}`,location):await api.post('/locations',location);modal.value=null;await load()}catch(e){error.value=errorMessage(e)}}
async function remove(kind:'products'|'locations',id:string){if(!confirm('Confirm this action?'))return;try{await api.delete(`/${kind}/${id}`);await load()}catch(e){error.value=errorMessage(e)}} function addAdjustment(){adjustment.productId=products.value[0]?.id??'';adjustment.locationId=locations.value.find(x=>x.isActive)?.id??'';modal.value='adjust'} async function adjust(){try{await api.post('/inventory/adjust',adjustment);modal.value=null;await load()}catch(e){error.value=errorMessage(e)}} onMounted(load);
</script>
<template><div class="page-heading"><div><p class="eyebrow">STOCK CONTROL</p><h1>Inventory workspace</h1><p>Products, locations and stock operations in one place.</p></div><button class="primary" @click="tab==='products'?addProduct():tab==='locations'?addLocation():addAdjustment()"><Plus :size="17"/>Add {{tab==='stock'?'adjustment':tab.slice(0,-1)}}</button></div><div class="tabs"><button :class="{active:tab==='stock'}" @click="tab='stock'">Stock</button><button :class="{active:tab==='products'}" @click="tab='products'">Products</button><button :class="{active:tab==='locations'}" @click="tab='locations'">Locations</button></div><div v-if="error" class="form-error">{{error}}</div><article class="panel table-panel"><div class="table-wrap">
<table v-if="tab==='stock'"><thead><tr><th>Product</th><th>Location</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Status</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><RouterLink :to="`/products/${r.product.id}`"><strong>{{r.product.name}}</strong></RouterLink><small>{{r.product.sku}}</small></td><td>{{r.location.name}}</td><td>{{r.quantityOnHand}}</td><td>{{r.quantityReserved}}</td><td>{{r.health.available}}</td><td><StatusBadge :status="r.health.status"/></td></tr></tbody></table>
<table v-else-if="tab==='products'"><thead><tr><th>Product</th><th>Category</th><th>Cost</th><th>Sale</th><th>Thresholds</th><th>Actions</th></tr></thead><tbody><tr v-for="p in products" :key="p.id"><td><RouterLink :to="`/products/${p.id}`"><strong>{{p.name}}</strong></RouterLink><small>{{p.sku}}</small></td><td>{{p.category}}</td><td>{{p.costPrice}}</td><td>{{p.defaultSalePrice}}</td><td>Min {{p.minimumStock}} · Reorder {{p.reorderPoint}}</td><td><button class="icon-button" @click="editProduct(p)"><Pencil :size="16"/></button><button class="icon-button danger" @click="remove('products',p.id)"><Trash2 :size="16"/></button></td></tr></tbody></table>
<table v-else><thead><tr><th>Name</th><th>Type</th><th>City</th><th>Address</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="x in locations" :key="x.id"><td><strong>{{x.name}}</strong></td><td>{{x.type.replaceAll('_',' ')}}</td><td>{{x.city}}, {{x.country}}</td><td>{{x.address}}</td><td><StatusBadge :status="x.isActive?'ACTIVE':'INACTIVE'"/></td><td><button class="icon-button" @click="editLocation(x)"><Pencil :size="16"/></button><button class="icon-button danger" @click="remove('locations',x.id)"><Trash2 :size="16"/></button></td></tr></tbody></table></div><div v-if="tab==='stock'&&!rows.length" class="empty"><Boxes/><strong>No stock yet</strong></div></article>
<div v-if="modal" class="modal-backdrop" @click.self="modal=null"><form class="modal" @submit.prevent="modal==='product'?saveProduct():modal==='location'?saveLocation():adjust()"><h2>{{editingId?'Edit':'Add'}} {{modal}}</h2><template v-if="modal==='product'"><div class="form-row"><label>SKU<input v-model="product.sku" required/></label><label>Name<input v-model="product.name" required/></label></div><div class="form-row"><label>Category<input v-model="product.category" required/></label><label>Unit<input v-model="product.unit" required/></label></div><div class="form-row"><label>Cost price<input v-model.number="product.costPrice" type="number" min="0"/></label><label>Sale price<input v-model.number="product.defaultSalePrice" type="number" min="0"/></label></div><div class="form-row"><label>Minimum stock<input v-model.number="product.minimumStock" type="number" min="0"/></label><label>Reorder point<input v-model.number="product.reorderPoint" type="number" min="0"/></label></div></template><template v-else-if="modal==='location'"><label>Name<input v-model="location.name" required/></label><label>Type<select v-model="location.type"><option>WAREHOUSE</option><option>BRANCH</option><option>STORE</option><option>DISTRIBUTION_CENTER</option></select></label><div class="form-row"><label>Country<input v-model="location.country" required/></label><label>City<input v-model="location.city" required/></label></div><label>Address<input v-model="location.address" required/></label></template><template v-else><label>Product<select v-model="adjustment.productId"><option v-for="p in products" :key="p.id" :value="p.id">{{p.name}}</option></select></label><label>Location<select v-model="adjustment.locationId"><option v-for="x in locations.filter(l=>l.isActive)" :key="x.id" :value="x.id">{{x.name}}</option></select></label><label>Quantity change<input v-model.number="adjustment.delta" type="number" required/></label><label>Reason<input v-model="adjustment.reason" required/></label></template><div class="modal-actions"><button type="button" class="secondary" @click="modal=null">Cancel</button><button class="primary">Save</button></div></form></div></template>
